export const transactionsData =[
    {
      id: 1,
      date: '2026-02-01',
      description: 'Groceries',
      category: 'Food',
      type: 'Expense',
      amount: -82.35,
    },
    {
      id: 2,
      date: '2026-02-03',
      description: 'Paycheck',
      category: 'Income',
      type: 'Income',
      amount: 2200,
    },
    {
      id: 3,
      date: '2026-02-05',
      description: 'Transit card',
      category: 'Transport',
      type: 'Expense',
      amount: -45.5,
    },
    {
      id: 4,
      date: '2026-02-06',
      description: 'Coffee',
      category: 'Food',
      type: 'Expense',
      amount: -6.25,
    },
    {
      id: 5,
      date: '2026-02-08',
      description: 'Gift',
      category: 'Misc',
      type: 'Income',
      amount: 120,
    },
    {
      id: 6,
      date: '2026-02-09',
      description: 'Gym',
      category: 'Health',
      type: 'Expense',
      amount: -55,
    },
  ]