import { Transaction } from '@/types/transactions'

export const transactionsData: Transaction[] = [
  {
    id: 1,
    date: '2026-02-01',
    description: 'Groceries',
    category: 'Food',
    type: 'Expense',
    amount: -82.35,
  },
  {
    id: 2,
    date: '2026-02-03',
    description: 'Paycheck',
    category: 'Income',
    type: 'Income',
    amount: 2200,
  },
  {
    id: 3,
    date: '2026-02-05',
    description: 'Transit card',
    category: 'Transport',
    type: 'Expense',
    amount: -45.5,
  },
  {
    id: 4,
    date: '2026-02-06',
    description: 'Coffee',
    category: 'Food',
    type: 'Expense',
    amount: -6.25,
  },
  {
    id: 5,
    date: '2026-02-08',
    description: 'Gift',
    category: 'Misc',
    type: 'Income',
    amount: 120,
  },
  {
    id: 6,
    date: '2026-02-09',
    description: 'Gym',
    category: 'Health',
    type: 'Expense',
    amount: -55,
  },
  {
    id: 7,
    date: '2026-01-28',
    description: 'Internet bill',
    category: 'Utilities',
    type: 'Expense',
    amount: -62.9,
  },
  {
    id: 8,
    date: '2026-01-25',
    description: 'Freelance project',
    category: 'Income',
    type: 'Income',
    amount: 480,
  },
  {
    id: 9,
    date: '2026-01-20',
    description: 'Dinner out',
    category: 'Food',
    type: 'Expense',
    amount: -38.4,
  },
  {
    id: 10,
    date: '2026-01-14',
    description: 'Electricity',
    category: 'Utilities',
    type: 'Expense',
    amount: -74.15,
  },
  {
    id: 11,
    date: '2025-12-30',
    description: 'Year-end bonus',
    category: 'Income',
    type: 'Income',
    amount: 950,
  },
  {
    id: 12,
    date: '2025-12-21',
    description: 'Holiday gifts',
    category: 'Shopping',
    type: 'Expense',
    amount: -210.75,
  },
  {
    id: 13,
    date: '2025-12-10',
    description: 'Pharmacy',
    category: 'Health',
    type: 'Expense',
    amount: -24.2,
  },
  {
    id: 14,
    date: '2025-11-27',
    description: 'Salary',
    category: 'Income',
    type: 'Income',
    amount: 2200,
  },
  {
    id: 15,
    date: '2025-11-15',
    description: 'Rent',
    category: 'Housing',
    type: 'Expense',
    amount: -1200,
  },
  {
    id: 16,
    date: '2025-11-03',
    description: 'Train pass',
    category: 'Transport',
    type: 'Expense',
    amount: -52,
  },
  {
    id: 17,
    date: '2025-10-22',
    description: 'Concert tickets',
    category: 'Entertainment',
    type: 'Expense',
    amount: -95,
  },
  {
    id: 18,
    date: '2025-10-12',
    description: 'Sold old laptop',
    category: 'Income',
    type: 'Income',
    amount: 300,
  },
  {
    id: 19,
    date: '2025-09-29',
    description: 'Groceries bulk',
    category: 'Food',
    type: 'Expense',
    amount: -129.6,
  },
  {
    id: 20,
    date: '2025-09-18',
    description: 'Car insurance',
    category: 'Insurance',
    type: 'Expense',
    amount: -310,
  },
  {
    id: 21,
    date: '2025-08-31',
    description: 'Tax refund',
    category: 'Income',
    type: 'Income',
    amount: 640,
  },
  {
    id: 22,
    date: '2025-08-10',
    description: 'Weekend trip',
    category: 'Travel',
    type: 'Expense',
    amount: -186.45,
  },
  {
    id: 23,
    date: '2025-07-25',
    description: 'Streaming subscription',
    category: 'Entertainment',
    type: 'Expense',
    amount: -14.99,
  },
  {
    id: 24,
    date: '2025-07-03',
    description: 'Part-time tutoring',
    category: 'Income',
    type: 'Income',
    amount: 260,
  },
]
